In [1]:
import numpy as np

In [2]:
# Define the parameters of the network
input_neuron = 2    # Number of input neurons
hidden_neuron = 4   # Number of hidden neurons
output_neuron = 1   # Number of output neurons
learning_rate = 0.1
epochs = 10000

In [3]:
# Define the training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

In [4]:
# Initialize the weights with random values
W1 = np.random.randn(input_neuron, hidden_neuron) * 0.01
W2 = np.random.randn(hidden_neuron, output_neuron) * 0.01

In [5]:
# Initialize the biases with random values
b1 = np.random.randn(1, hidden_neuron) * 0.01
b2 = np.random.randn(1, output_neuron) * 0.01

In [6]:
# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [11]:
# Train the network using backpropagation
for i in range(epochs):
    # Forward pass
    hidden_layer_input = np.dot(X, W1) + b1
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, W2) + b2
    output_layer_output = sigmoid(output_layer_input)

 #Backward pass
    output_error = Y - output_layer_output
    output_delta = output_error * sigmoid_derivative(output_layer_output)

    hidden_error = output_delta.dot(W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

In [12]:
#Test the network with some example inputs
x_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_test = np.array([[0], [1], [1], [0]])

hidden_layer_input = np.dot(x_test, W1) + b1
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, W2) + b2
output_layer_output = sigmoid(output_layer_input)

print("Input:")
print(x_test)
print("Output:")
print(output_layer_output)
print("Expected Output:")
print(y_test)

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Output:
[[0.50438979]
 [0.50438322]
 [0.50438868]
 [0.50438211]]
Expected Output:
[[0]
 [1]
 [1]
 [0]]
