## Write a python program to design a Hopfield Network which stores 4 vectors

In [1]:
#Hebbian Rule
import numpy as np 

In [2]:
class HopfieldNetwork:
    def __init__(self, n_neurons): 
        self.weights = np.zeros((n_neurons, n_neurons))

    def train(self, patterns):
        for pattern in patterns:
            self.weights += np.outer(pattern, pattern)
            np.fill_diagonal(self.weights, 0)
            print(self.weights)

    '''def predict(self, pattern):
        energy = -0.5 * ((pattern @ self.weights) @ pattern) 
        return np.sign((pattern @ self.weights) + energy)'''
    
    def predict(self, pattern, max_iter=10):
        for _ in range(max_iter):
            new_pattern = np.sign(np.dot(pattern, self.weights))
            if np.array_equal(new_pattern, pattern):
                return new_pattern
            pattern = new_pattern
        return pattern

In [3]:
'''patterns = np.array([
                [1, 1, -1, -1],
                [-1, -1, 1, 1],
                [1, -1, 1, -1],
                [-1, 1, -1, 1]
                ])'''
patterns = np.array([
                [0,1,0],
                [1,0,1],
                [0,1,0],
                ])
n_neurons = 3

In [4]:
network = HopfieldNetwork(n_neurons)

In [5]:
network.train(patterns)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [6]:
for pattern in patterns:
    prediction = network.predict(pattern) 
    print('Input pattern:', pattern) 
    print('Predicted pattern:', prediction)

Input pattern: [0 1 0]
Predicted pattern: [0. 0. 0.]
Input pattern: [1 0 1]
Predicted pattern: [1. 0. 1.]
Input pattern: [0 1 0]
Predicted pattern: [0. 0. 0.]
